/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Francy
 */
public class Tangente extends javax.swing.JFrame {

    /**
     * Creates new form Bisezione
     */
    public Tangente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        myCanvas = new java.awt.Canvas();
        aTXTField = new javax.swing.JTextField();
        bTXTField = new javax.swing.JTextField();
        maxIterationTXTField = new javax.swing.JTextField();
        epsTXTField = new javax.swing.JTextField();
        resTXTField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        drawFunction = new javax.swing.JButton();
        _aTXTField = new javax.swing.JTextField();
        _cTXTField = new javax.swing.JTextField();
        _bTXTField = new javax.swing.JTextField();
        _dTXTField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        deltaTXTField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Metodo di Newton-Rapshon");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        myCanvas.setPreferredSize(new java.awt.Dimension(400, 400));

        aTXTField.setText("30");
        aTXTField.setToolTipText("Inserire valore : ex. 20");

        bTXTField.setText("115");
        bTXTField.setToolTipText("Inserire valore : ex. 100");

        maxIterationTXTField.setText("1000");
        maxIterationTXTField.setToolTipText("Inserire valore : ex. 1000");

        epsTXTField.setText("0.00001");
        epsTXTField.setToolTipText("Inserire valore : ex. 0.0001");

        resTXTField.setEnabled(false);

        jLabel6.setText("Newton-Raphson applicato a un polinomio di terzo grado");

        jLabel1.setText("Inserire valore estremo b");

        jLabel2.setText("Inserire valore estremo a");

        jLabel3.setText("Valore approssimato radice");

        jLabel4.setText("Inserire valore iterazioni massime");

        jLabel5.setText("Inserire valore epsilon");

        drawFunction.setText("Draw function and get tangent");
        drawFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawFunctionActionPerformed(evt);
            }
        });

        _aTXTField.setText("0.0002");
        _aTXTField.setToolTipText("ex. 0.0002");
        _aTXTField.setMinimumSize(new java.awt.Dimension(60, 20));
        _aTXTField.setPreferredSize(new java.awt.Dimension(60, 25));

        _cTXTField.setText("-2");
        _cTXTField.setToolTipText("ex. -2");
        _cTXTField.setMinimumSize(new java.awt.Dimension(60, 20));
        _cTXTField.setPreferredSize(new java.awt.Dimension(60, 25));

        _bTXTField.setText("0.006");
        _bTXTField.setToolTipText("ex. -0.001");
        _bTXTField.setMinimumSize(new java.awt.Dimension(60, 20));
        _bTXTField.setPreferredSize(new java.awt.Dimension(60, 25));

        _dTXTField.setText("0");
        _dTXTField.setToolTipText("ex. 50");
        _dTXTField.setMinimumSize(new java.awt.Dimension(60, 20));
        _dTXTField.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabel7.setText("a");

        jLabel8.setText("c");

        jLabel9.setText("d");

        jLabel10.setText("b");

        deltaTXTField.setText("5");
        deltaTXTField.setToolTipText("Inserire valore : ex. 6");

        jLabel11.setText("Inserire valore delta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(aTXTField)
                                .addComponent(bTXTField, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(maxIterationTXTField, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(resTXTField, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(drawFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(epsTXTField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(deltaTXTField)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_aTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_cTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(_dTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(_bTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_aTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(_bTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_cTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(_dTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(bTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(maxIterationTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(epsTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deltaTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(resTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drawFunction))
                    .addComponent(myCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawFunctionActionPerformed
        Graphics g = myCanvas.getGraphics();
        
        int hW = myCanvas.getWidth() / 2;
        int hH = myCanvas.getHeight() / 2;
        
        //Clear canvas
        g.clearRect(0, 0, myCanvas.getWidth(), myCanvas.getHeight());
        
        //Y Axis
        g.drawLine(hW, myCanvas.getHeight(), hW, -myCanvas.getHeight());
        
        //X Axis
        g.drawLine(0, hH, myCanvas.getWidth(), hH);
        
        g.drawString("y", hW + 3, 7);
        g.drawString("x", hW * 2 - 5, hH - 3);
        
        double _a = Double.parseDouble(_aTXTField.getText());
        double _b = Double.parseDouble(_bTXTField.getText());
        double _c = Double.parseDouble(_cTXTField.getText());
        double _d = Double.parseDouble(_dTXTField.getText());
        
        double a   = Double.parseDouble(aTXTField.getText());
        double b   = Double.parseDouble(bTXTField.getText());
        
        int _maxIteration = Integer.parseInt(maxIterationTXTField.getText());
        float _eps = Float.parseFloat(epsTXTField.getText());
        float _delta = Float.parseFloat(deltaTXTField.getText());
        
        Funzione funzioneCubica = new funzioneCubica(_a, _b, _c, _d);
        funzioneCubica.draw(myCanvas, Color.red);
        
        TangentMethod tangent = new TangentMethod(_maxIteration, _eps, _delta, funzioneCubica);
        double tan = tangent.calcola(a, b);
        
        int Xa = (int) (hW + a);
        int Xb = (int) (hW + b);
       
        g.drawString("a", Xa + 3, hH - 3);
        g.drawString("b", Xb + 3, hH - 3);
        
        g.fillOval(Xa - 3, hH - 3, 6, 6);
        g.fillOval(Xb - 3, hH - 3, 6, 6);
        
        g.drawLine(Xa, hH * 2, Xa, -hH);
        g.drawLine(Xb, hH * 2, Xb, -hH);
        
        if (tan >= 0) {
            g.setColor(Color.magenta);
            
            int Xm = (int) (hW + tan);
            
            g.drawString("m", Xm + 3, hH + 12);
            g.fillOval(Xm - 3, hH - 3, 6, 6);
            //g.drawLine(Xm, hH * 2, Xm, -hH);
            
            resTXTField.setText(String.valueOf(tan));  
            double K = tangent.Kt(Xm);
            //System.out.println(K);
            rettaTangente rettaTan = new rettaTangente(K, Xm);
            System.out.println(rettaTan.calcola(100));
            
            rettaTan.draw(myCanvas, Color.magenta);         
        }             
    }//GEN-LAST:event_drawFunctionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _aTXTField;
    private javax.swing.JTextField _bTXTField;
    private javax.swing.JTextField _cTXTField;
    private javax.swing.JTextField _dTXTField;
    private javax.swing.JTextField aTXTField;
    private javax.swing.JTextField bTXTField;
    private javax.swing.JTextField deltaTXTField;
    private javax.swing.JButton drawFunction;
    private javax.swing.JTextField epsTXTField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxIterationTXTField;
    private java.awt.Canvas myCanvas;
    private javax.swing.JTextField resTXTField;
    // End of variables declaration//GEN-END:variables
}